{
 "title": "Common Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "High and Bulk Latency p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "high_latency_p99", "legendFormat": "__auto" },
    { "expr": "bulk_latency_p99", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "High and Bulk Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "high_throughput", "legendFormat": "__auto" },
    { "expr": "bulk_throughput", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "High and Bulk Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "high_latency_p95", "legendFormat": "__auto" },
    { "expr": "bulk_latency_p95", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "High and Bulk Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "high_queue_lag", "legendFormat": "__auto" },
    { "expr": "bulk_queue_lag", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "High and Bulk Latency p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "bulk_latency_p50", "legendFormat": "__auto" },
    { "expr": "high_latency_p50", "legendFormat": "__auto" }
   ]
  }
 ]
}